/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f1f1f1",
        "on-primary": "#ffffff",
        "on-surface-variant": "#5a4042",
        "secondary-container": "#feb700",
        "surface-tint": "#b81840",
        "on-primary-container": "#ffafb5",
        "on-surface": "#1a1c1c",
        "on-error": "#ffffff",
        "primary": "#7a0024",
        "on-tertiary-fixed-variant": "#474747",
        "outline-variant": "#e2bec0",
        "surface-bright": "#f9f9f9",
        "tertiary": "#3a3a3a",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-secondary-container": "#6b4b00",
        "on-primary-fixed-variant": "#91002d",
        "primary-fixed-dim": "#ffb2b8",
        "primary-container": "#a50034",
        "on-secondary": "#ffffff",
        "secondary": "#7c5800",
        "on-tertiary-container": "#c4c4c4",
        "secondary-fixed-dim": "#ffba20",
        "on-background": "#1a1c1c",
        "on-secondary-fixed-variant": "#5e4200",
        "surface-dim": "#dadada",
        "on-primary-fixed": "#40000f",
        "surface-container-highest": "#e2e2e2",
        "outline": "#8e7071",
        "inverse-surface": "#2f3131",
        "surface-container": "#eeeeee",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdadb",
        "surface": "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        "error-container": "#ffdad6",
        "background": "#f9f9f9",
        "on-secondary-fixed": "#271900",
        "surface-variant": "#e2e2e2",
        "inverse-primary": "#ffb2b8",
        "tertiary-container": "#515151",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffdea8",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-fixed": "#1b1b1b",
        "surface-container-low": "#f3f3f3"
      },
      fontFamily: {
        "headline": ["Epilogue"],
        "body": ["Newsreader"],
        "label": ["Space Grotesk"]
      },
      borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
    },
  },
  plugins: [],
}