import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Poppins(
  {
    variable: "--font-geist-sans",
    subsets: ["latin"],
    weight: ["400", "700"],
  }
);


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          <div className="flex-1">
            <div className="p-15">
              <a href="/" className="text-3xl font-bold underline">Routine</a>
            </div>
            <div className="p-15 font-bold">
              <ul className="list-none gap-5 flex flex-col">
                <li>
                  <a className="hover:bg-gray-100 p-2 rounded" href="/teachers">Teachers</a>
                </li>
                <li>
                  <a className="hover:bg-gray-100 p-2 rounded" href="/classrooms">Classrooms</a>
                </li>
                <li>
                  <a className="hover:bg-gray-100 p-2 rounded" href="/sections">Sections</a>
                </li>
                <li>
                  <a className="hover:bg-gray-100 p-2 rounded" href="/courses">Courses</a>
                </li>
              </ul>
            </div>
          </div>
          <div className="flex-4 p-15">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
